#!/bin/sh

checkError()
{
    if [ "${1}" -ne "0" ]; then
        echo "*** Error: ${2}"
        exit ${1}
    fi
}

if [ ! -f $STANDALONE_TOOLCHAIN_PATH/sysroot/usr/lib/libxml2.a ]; then
    echo "Building libxml2"

	if [ ! -d libxml2-2.9.0 ]; then
	    if [ ! -f libxml2-2.9.0.tar.gz ]; then
	        curl ftp://xmlsoft.org/libxml2/libxml2-2.9.0.tar.gz > libxml2-2.9.0.tar.gz
	    fi
		
	    tar -xzf libxml2-2.9.0.tar.gz
		
	    pushd libxml2-2.9.0
	    # remove tests that needs glob.h
	    patch -p1 -i ../libxml2_tests.patch
		popd
	fi

	pushd libxml2-2.9.0

    # build with gcc instead of clang
    # using clang produce an error missing symbol 'nan'
    CC="$GCC_ARM" LD="$LD_ARM" CXX="$CLANGPP_ARM" CPPFLAGS="$SYSROOTFLAGS_ARM" CFLAGS="$SYSROOTFLAGS_ARM" AR="$AR_ARM" OBJDUMP="$OBJDUMP_ARM" RANLIB="$RANLIB_ARM" ./configure --prefix=$STANDALONE_TOOLCHAIN_PATH/sysroot/usr --host="arm-linux-androideabi" --with-sysroot=$STANDALONE_TOOLCHAIN_PATH/sysroot --disable-shared
    checkError $? "configure libxml2 failed"

    make install
    checkError $? "Make install libxml2 failed"
    cd $BUILDROOT
fi