#!/bin/bash

./BreakPointsConvert ../MiraiTests.xcodeproj/xcuserdata/chyhfj.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist ./obj/local/armeabi/gdbbreakpoint.setup
ndk-gdb --start --exec=./obj/local/armeabi/gdbbreakpoint.setup
