#!/bin/sh

checkError()
{
    if [ "${1}" -ne "0" ]; then
        echo "*** Error: ${2}"
        exit ${1}
    fi
}

pushd ffi
./buildFFI
checkError $? "build ffi failed"

popd

pushd libxml
./buildLibXML
checkError $? "build libxml failed"

popd

pushd dispatch
./buildDispatch
checkError $? "build dispatch failed"

popd

pushd objc
./buildObjC2
checkError $? "build objc2 failed"
popd