#!/bin/bash

pushd `pwd`/`dirname $0`
FILE_ROOT=`pwd`
popd

pushd $FILE_ROOT/../android-toolchain-arm/arm-linux-androideabi/bin

if [ -f realld ]; then
	echo "already pached"
	exit 1
fi

#rename ld
mv ld realld
cp $FILE_ROOT/ld ld
popd
