#!/bin/sh

pushd `pwd`/`dirname $0`
SCRIPT_ROOT=`pwd`
popd

checkError()
{
    if [ "${1}" -ne "0" ]; then
        echo "*** Error: ${2}"
        exit ${1}
    fi
}

# TODO: before build libobjc2, needs build libdispatch
if [ ! -f $STANDALONE_TOOLCHAIN_PATH/sysroot/usr/lib/libobjc.so ]; then

	if [ ! -d libobjc2 ]; then
		svn co http://svn.gna.org/svn/gnustep/libs/libobjc2/trunk libobjc2

		pushd libobjc2

		# apply patches
		patch -p0 -i ../libobjc2_SONAME.patch
		patch -p0 -i ../libobjc_android_test.diff
		popd
	fi

	mkdir -p libobjc2/Build
	pushd libobjc2/Build
	#clean
	rm -rf ./*

	# disable test, some tests failed due to cross-compiled 
	cmake -DTESTS=0 -DCMAKE_TOOLCHAIN_FILE=$SCRIPT_ROOT/../../toolchain.cmake -DCMAKE_FIND_ROOT_PATH=$STANDALONE_TOOLCHAIN_PATH/sysroot -DCMAKE_INSTALL_PREFIX=/usr ..
	make
	checkError $? "build objc2 failed"
	
	make install DESTDIR=$STANDALONE_TOOLCHAIN_PATH/sysroot
	checkError $? "make install objc2 failed"
	
	popd

fi